# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Thoughts for the Pack
tagline:          ''
description:      ''
url:              http://mswolfe.github.io
baseurl:          /
repository:	      mswolfe/mswolfe.github.io

author:
  name:           'Michael Wolfe'
  github_user:    mswolfe
  twitter_user:   mwooolfe

paginate:         5
paginate_path: 	  "page:num"

exclude: [reveal.js]

gems: [jekyll-paginate]