# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thoughts for the Pack
#email: mwoolfe@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  A little corner of the web for me to store some of the tips and tricks
  I encountered over the years.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mswolfe.github.io" # the base hostname & protocol for your site
twitter_username: mwooolfe
github_username:  mswolfe

# Build settings
markdown: kramdown
