# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Thoughts for the Pack
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://mswolfe.github.io
baseurl:          /

author:
  name:           'Michael Wolfe'
  url:            https://twitter.com/mwooolfe

paginate:         5
paginate_path: 	  "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mswolfe

gems: [jekyll-paginate]
 # This will require each of these gems automatically.